before_install:
  - echo 'add_package_checks()' > /home/travis/build/bjmt/universalmotif/tic.R
  - R -q -e 'install.packages(c("remotes", "curl", "covr")); remotes::install_github("ropenscilabs/tic"); remotes::install_github("GuangchuangYu/ggtree"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success:
  - R -q -e 'covr::codecov(type=c("tests","examples"),quiet=FALSE)'
  - R -q -e 'BiocManager::install("BiocCheck")'
  - R -q -e 'BiocCheck::BiocCheck("/home/travis/build/bjmt/universalmotif", `no-check-vignettes`=TRUE, `quit-with-status`=TRUE, `new-package`=TRUE)'
after_failure: R -q -e 'tic::after_failure()'
after_script: R -q -e 'tic::after_script()'

# Header
language: r
sudo: false
dist: trusty
cache: packages
latex: true

r: bioc-devel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgsl0-dev
      - ghostscript
      - texlive-fonts-recommended
      - g++-7

branches:
  only:
    - master

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

#services
services:
