# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

before_install: R -q -e 'install.packages(c("remotes", "curl")); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success:
  - R -q -e 'tic::after_success()'
  - R -q -e 'BiocManager::install("BiocCheck")'
  - R -q -e 'BiocCheck::BiocCheck("/home/travis/build/bjmt/universalmotif", "--no-build-vignettes")'
after_failure: R -q -e 'tic::after_failure()'
after_script: R -q -e 'tic::after_script()'

# Header
language: r
sudo: false
dist: trusty
cache: packages
latex: false

r: bioc-devel

addons:
  apt:
    packages:
      - libgsl0-dev

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#services
services:
