language: r
cache: packages
sudo: required
latex: false

r:
  - bioc-release
  # - bioc-devel

r_packages:
  - covr

bioc_required: true

bioc_packages:
  - BiocCheck

bioc_check: true

# after_script:
  # - ls -lah
  # - FILE=$(ls -1t *.tar.gz | head -n 1)
  # - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"

after_success:
  # - Rscript -e 'library(covr);package_coverage()'
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    recipients:
      - b2tremblay@uwaterloo.ca
    on_success: change
    on_failure: always

# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/
#
# language: c
# sudo: required
# dist: trusty
#
# before_install:
#   - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
#   - ./run.sh bootstrap
#
# install:
#   - ./run.sh install_aptget r-cran-knitr r-cran-rmarkdown
#
# script:
#   - ./run.sh run_tests
#
# after_failure:
#   - ./run.sh dump_logs
#
# after_success:
#   - ./run.sh coverage
#
# notifications:
#   email:
#     on_success: change
#     on_failure: change
