language: r
cache: packages
sudo: required

r:
  - bioc-release
  # - bioc-devel

r_packages:
  - covr

bioc_required: true

# bioc_packages:
  # - BiocCheck

# after_script:
  # - ls -lah
  # - FILE=$(ls -1t *.tar.gz | head -n 1)
  # - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"

after_success:
  # - Rscript -e 'library(covr);package_coverage()'
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    recipients:
      - b2tremblay@uwaterloo.ca
    on_success: change
    on_failure: always
