language: r
cache: packages
sudo: required
latex: false

r:
  - bioc-release
  # - bioc-devel

r_packages:
  - covr

r_binary_packages:
  - r-bioc-annotationdbi
  - r-bioc-annotationhub
  - r-bioc-biobase
  - r-bioc-biocgenerics
  - r-bioc-biocinstaller
  - r-bioc-biocparallel
  - r-bioc-biostrings
  - r-bioc-biovizbase
  - r-bioc-dirichletmultinomial
  - r-bioc-ensembldb
  - r-bioc-genomeinfodb
  - r-bioc-genomicalignments
  - r-bioc-genomicfeatures
  - r-bioc-genomicranges
  - r-bioc-go.db
  - r-bioc-iranges
  - r-bioc-keggrest
  - r-bioc-rsamtools
  - r-bioc-rtracklayer
  - r-bioc-s4vectors
  - r-bioc-summarizedexperiment
  - r-cran-ade4
  - r-cran-ape
  - r-cran-bh
  - r-cran-codetools
  - r-cran-curl
  - r-cran-devtools
  - r-cran-dplyr
  - r-cran-r.oo
  - r-cran-r.utils
  - r-cran-r6
  - r-cran-rcpp
  - r-cran-rcurl
  - r-cran-readr
  - r-cran-roxygen2
  - r-cran-sourcetools
  - r-cran-stringi
  - r-cran-utf8
  - r-cran-fansi
  - r-cran-plyr
  - r-cran-reshape
  - r-cran-reshape2
  - r-cran-rmarkdown
  - r-cran-base64enc
  - r-cran-yaml
  - r-cran-magrittr
  - r-cran-markdown
  - r-cran-ggplot2
  - r-cran-git2r
  - r-cran-gtools
  - r-cran-digest
  - r-cran-later
  - r-cran-lazyeval
  - r-cran-promises
  - r-cran-data.table
  - r-cran-matrixstats
  - r-cran-evd
  - r-cran-evaluate
  - r-cran-rsqlite
  - r-cran-bit
  - r-cran-bit64
  - r-cran-mixtools
  - r-cran-httpuv
  - r-cran-bibtex
  - r-cran-praise

bioc_required: true

bioc_packages:
  - BiocCheck

bioc_check: true

# after_script:
  # - ls -lah
  # - FILE=$(ls -1t *.tar.gz | head -n 1)
  # - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"

after_success:
  # - Rscript -e 'library(covr);package_coverage()'
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    recipients:
      - b2tremblay@uwaterloo.ca
    on_success: change
    on_failure: always

# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/
#
# language: c
# sudo: required
# dist: trusty
#
# before_install:
#   - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
#   - ./run.sh bootstrap
#
# install:
#   - ./run.sh install_aptget r-cran-knitr r-cran-rmarkdown
#
# script:
#   - ./run.sh run_tests
#
# after_failure:
#   - ./run.sh dump_logs
#
# after_success:
#   - ./run.sh coverage
#
# notifications:
#   email:
#     on_success: change
#     on_failure: change
